# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build 'juxce.tuneage.pac.sln' --configuration $(buildConfiguration)
  displayName: 'Build juxce.tuneage.pac solution'
     
- script: dotnet test 'juxce.tuneage.pac.test.unit' --configuration $(buildConfiguration) --logger trx
  displayName: 'Run unit tests'
 
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
 
- script: dotnet publish 'juxce.tuneage.pac\juxce.tuneage.pac.csproj' --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'publish function app'

# Archive Files
# Archive files using compression formats such as .7z, .rar, .tar.gz, and .zip.
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app' 
    #includeRootFolder: 
    archiveType: 'zip' 
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true 
  
- task: PublishBuildArtifacts@1
  displayName: 'Publishing app artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    artifactName: app
 
- task: CopyFiles@2
  displayName: 'Copy integration tests'
  inputs:
    sourceFolder: 'juxce.tuneage.pac.test.integration'
    targetFolder: '$(Build.ArtifactStagingDirectory)/postman'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish postman tests'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/postman'
    artifactName: postman